import {createRequire} from 'node:module';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {resolve} from 'node:path';
const sdkRequire=createRequire(import.meta.resolve('@rarefriends/friendsdk/build'));
const {build}=sdkRequire('esbuild');
const samplePath=resolve('node_modules/@rarefriends/friendsdk/examples/fishing/sample-sprites.ts');
const sampleSource=await readFile(samplePath,'utf8');
const section=sampleSource.split('"7730": decodeGenerationSprites')[1]?.split(']),')[0];
const frames=[...(section??'').matchAll(/0x[0-9a-f]+n/g)].map(([word])=>word);
if(frames.length!==64)throw new Error('Expected 64 pinned sample artwork frames');
const outdir=resolve(process.argv[2] && process.argv[2] !== 'build' ? process.argv[2] : 'dist');await mkdir(outdir,{recursive:true});
await build({entryPoints:['games/rare-flip/demo.tsx'],outdir,entryNames:'demo',bundle:true,format:'iife',platform:'browser',target:'es2022',jsx:'automatic',minify:true,define:{'process.env.NODE_ENV':'"production"'},loader:{'.png':'file'},assetNames:'demo-assets/[name]-[hash]',plugins:[{name:'sample-art',setup(plugin){plugin.onResolve({filter:/^rare-flip-demo-sample$/},()=>({path:'sample',namespace:'demo-sample'}));plugin.onLoad({filter:/.*/,namespace:'demo-sample'},()=>({contents:`import {decodeGenerationSprites} from '@rarefriends/friendsdk/sprites'; export default decodeGenerationSprites(7730n,5,7730,[${frames.join(',')}]);`,resolveDir:resolve('.'),loader:'js'}));}}]});
await writeFile(resolve(outdir,'demo.html'),`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; media-src 'self' blob:; connect-src 'none'; base-uri 'none'; form-action 'none'; frame-src 'none'"><title>Rare Flip — No-wallet Demo</title><link rel="stylesheet" href="./demo.css"></head><body><main id="root"></main><script src="./demo.js"></script></body></html>`);
console.log('Built no-wallet gameplay demo with local sample artwork and network-disabled CSP.');
